site_name: Respect Validation (Python)
site_description: Python version of the most awesome validation engine
site_url: https://gurkin33.github.io/respect_validation/
repo_url: https://github.com/gurkin33/respect_validation
extra_css: [css/extra.css]
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  palette:
    primary: light green
