name: Code coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Respect Validation
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install requirements
#      run: pip install -r requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Run tests and collect coverage
      run: pytest

    - name: Generate coverage report
      run: coverage report -m
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3